### ISSUE TITLE
Intel Galileo 2

### ISSUE THREAD

**Issue by luisnf4** [TMRh20/tmrh20.github.io#1]
Hi , i tried to install the lib in the intel galileo 2 with sudo make install -B RF24_MRAA=1 but i can't, the compiler shows many errors, i don't now if i have to do another step to compile or if there is an issue with the library. Thanks

**Comment by TMRh20** [comment]
1. Please post the compile output/errors. (note: Surround output with three ``` code here ``` like `this to format it as code` )
2. Have you installed and tested MRAA successfully? See http://iotdk.intel.com/docs/master/mraa/building.html
